# Generated by Django 3.2.18 on 2023-04-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_servicos_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='cargo',
            field=models.CharField(default='atendente', max_length=100, verbose_name='Cargo'),
        ),
    ]
