# Generated by Django 3.2.18 on 2023-04-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cargo_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='cargo',
            field=models.CharField(default='estagiário', max_length=100, verbose_name='Cargo'),
        ),
    ]
