# Generated by Django 3.2.18 on 2023-04-15 23:11

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='icone',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 400, 'width': 640}}, verbose_name='Icone'),
        ),
    ]
