# Generated by Django 3.2.18 on 2023-04-15 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20230415_2029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Features',
        ),
    ]
