# Generated by Django 3.2.18 on 2023-04-16 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_features_detalhe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='features',
            options={'verbose_name': 'Features', 'verbose_name_plural': 'Featureses'},
        ),
    ]
